// src/lib/components/ChangePassword.svelte
<script>
	let showModal = false;
</script>

<div>
	<button class="text-black text-xl text-center" on:click={() => (showModal = true)}>
		Change Password
	</button>
	<div class="modal modal-bottom sm:modal-middle" class:modal-open={showModal}>
		<div class="modal-box">
			<button
				class="btn btn-sm btn-circle absolute right-2 top-2 cursor-pointer"
				on:click={() => (showModal = false)}
			>
				✕
			</button>

			<!-- Old Password -->
			<p class="text-md mt-5 mb-3">Old Password</p>
			<input
				type="text"
				placeholder="Old Password"
				class="input input-bordered input-md w-full max-w-xs"
			/>
			<!-- New Password -->
			<p class="text-md mt-3 mb-3">New Password</p>
			<input
				type="text"
				placeholder="New Password"
				class="input input-bordered input-md w-full max-w-xs"
			/>
			<!-- Confirm New Password -->
			<p class="text-md mt-3 mb-3">Confirm New Password</p>
			<input
				type="text"
				placeholder="Confirm New Password"
				class="input input-bordered input-md w-full max-w-xs"
			/>

			<div class="modal-action">
				<button class="btn" on:click={() => (showModal = false)}> Change & Save </button>
			</div>
		</div>
	</div>
</div>

// src/app/components/Settings/ChangePassword.tsx
import * as React from "react";

export interface IChangePasswordProps {}

export default function ChangePassword(props: IChangePasswordProps) {
  return (
    <div>
      <label htmlFor="my-modal-6" className="text-black text-xl text-center">
        Change Password
      </label>
      <input type="checkbox" id="my-modal-6" className="modal-toggle" />
      <div className="modal modal-bottom sm:modal-middle">
        <div className="modal-box">
          <label
            htmlFor="my-modal-6"
            className="btn btn-sm btn-circle absolute right-2 top-2"
          >
            ✕
          </label>

          {/*Old Password*/}
          <p className="text-md mt-5 mb-3">Old Password</p>
          <input
            type="text"
            placeholder="Old Password"
            className="input input-bordered input-md w-full max-w-xs"
          />
          {/*New Password*/}
          <p className="text-md mt-3 mb-3">New Password</p>
          <input
            type="text"
            placeholder="New Password"
            className="input input-bordered input-md w-full max-w-xs"
          />
          {/*Confirm New Password*/}
          <p className="text-md mt-3 mb-3">Confirm New Password</p>
          <input
            type="text"
            placeholder="Confirm New Password"
            className="input input-bordered input-md w-full max-w-xs"
          />

          <div className="modal-action">
            <label htmlFor="my-modal-6" className="btn">
              Change & Save
            </label>
          </div>
        </div>
      </div>
    </div>
  );
}
