// src/lib/components/WalletActivity.svelte
<script lang="ts">
	import { walletAddress } from '$lib/store/store';
	import { ethers } from 'ethers';
	import { onMount } from 'svelte';

	let transactionHistory: any = [];

	const getTransactionHistory = async (address: string) => {
		const provider = new ethers.providers.EtherscanProvider('mainnet');

		transactionHistory = await provider.getHistory(address);
		console.log(transactionHistory);
	};

	onMount(() => {
		getTransactionHistory($walletAddress);
	});
</script>

<div class="flex flex-col mb-4">
	<label class="text-lg font-bold mb-2" for="transactions-table">Activity</label>
	<table class="w-full" id="transactions-table">
		<thead>
			<tr>
				<th class="px-4 py-2">Type</th>
				<th class="px-4 py-2">Hash</th>
				<th class="px-4 py-2">Amount</th>
				<th class="px-4 py-2">Date</th>
			</tr>
		</thead>
		<tbody>
			{#each transactionHistory as transaction}
				<tr>
					{#if transaction.from == $walletAddress}
						<td class="px-4 py-2">Sent</td>
					{:else if transaction.from !== $walletAddress}
						<td class="px-4 py-2">Received</td>
					{/if}
					<td class="px-4 py-2">{transaction.hash.substring(0, 6) + '...'}</td>
					<td class="px-4 py-2">
						{parseInt(transaction.value._hex, 16) / 10 ** 18} ETH
					</td>
					<td class="px-4 py-2">
						{new Date(transaction.timestamp * 1000).toLocaleString()}
					</td>
				</tr>
			{/each}
		</tbody>
	</table>
</div>

// src/app/components/Wallet/WalletActivity.tsx
import * as React from "react";

export interface IWalletActivityProps {}

export default function WalletActivity(props: IWalletActivityProps) {
  const transactions = [
    {
      type: "Send",
      asset: "BTC",
      amount: "0.1",
      date: "Jan 1, 2021",
    },
    {
      type: "Receive",
      asset: "ETH",
      amount: "0.5",
      date: "Jan 2, 2021",
    },
  ];
  return (
    <div className="flex flex-col mb-4">
      <label className="text-lg font-bold mb-2">Activity</label>
      <table className="w-full">
        <thead>
          <tr>
            <th className="px-4 py-2">Type</th>
            <th className="px-4 py-2">Asset</th>
            <th className="px-4 py-2">Amount</th>
            <th className="px-4 py-2">Date</th>
          </tr>
        </thead>
        <tbody>
          {transactions.map((transaction) => (
            <tr key={transaction.date}>
              <td className="px-4 py-2">{transaction.type}</td>
              <td className="px-4 py-2">{transaction.asset}</td>
              <td className="px-4 py-2">{transaction.amount}</td>
              <td className="px-4 py-2">{transaction.date}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}
