// src/routes/get-secret-key/create-password/+page.svelte
<script>
	import { redirect } from '@sveltejs/kit';

	let newPassword = '';
	let confirmPassword = '';
	let error = '';
	let termsAndConditions = true;

	const handleSubmit = () => {
		if (newPassword === confirmPassword && newPassword !== '' && newPassword.length >= 6 && termsAndConditions) {
			error = '';
			window.location.href = '/dashboard';
		} else if (newPassword.length < 6) {
			error = 'Password has to be at least 6 characters long';
		} else if (!termsAndConditions) {
			error = 'You need to accept the terms and conditions';
		} else {
			error = 'Passwords are not matching';
		}
	};
</script>

<h1 class="text-5xl text-left mb-2">CREATE YOUR PASSWORD</h1>
<h1 class={`text-lg text-left mb-3.5 ${error !== '' ? 'text-red-500' : ''}`}>
	{error !== '' ? error : 'You will use this to unlock your wallet'}
</h1>
<div>
	<h2 class="text-xl text-left mt-3 mb-1">New Password</h2>
	<input
		type="password"
		class="input input-bordered w-full"
		placeholder="New Password"
		bind:value={newPassword}
	/>
</div>
<br />
<div>
	<h2 class="text-xl text-left mt-3 mb-1">Confirm Password</h2>
	<input
		type="password"
		class="input input-bordered w-full"
		placeholder="Confirm Password"
		bind:value={confirmPassword}
	/>
</div>

<div class="divider" />

<div class="form-control">
	<label class="label cursor-pointer">
		<span class="label-text">
			I agree to the{' '}
			<span class="text-lime-700">Terms of Service</span>
		</span>
		<input
			type="checkbox"
			class="checkbox"
			checked={termsAndConditions}
			on:change={() => (termsAndConditions = !termsAndConditions)}
		/>
	</label>
</div>

{#if termsAndConditions}
	<button on:click={handleSubmit} class="btn btn-wide">Confirm</button>
{:else}
	<button disabled class="btn btn-wide">Confirm</button>
{/if}

// src/app/OnboardingPages/components/NewUser/CreatePassword.tsx
import * as React from 'react';
import { useState } from "react";
import { useNavigate } from "react-router-dom";

export default function CreatePassword() {
  const navigate = useNavigate();

  const [newPassword, setNewPassword] = useState("");
  const [confirmPassword, setConfirmPassword] = useState("");
  const [error, setError] = useState("");
  const [termsAndConditions, setTermsAndConditions] = useState(true);

  const handleSubmit = () => {
    if (
      newPassword === confirmPassword &&
      newPassword !== "" &&
      newPassword.length >= 6
    ) {
      setError("");
      navigate("/DashboardHome");
    } else if (newPassword.length < 6) {
      setError("Password has to be at least 6 characters long");
    } else {
      setError("Passwords are not matching");
    }
    return;
  };

  return (
    <div className="artboard phone-1 p-5">
      <h1 className="text-5xl text-left mb-2">CREATE YOUR PASSWORD</h1>
      <div>
        <h2 className="text-xl text-left mt-3 mb-1">New Password</h2>
        <input
          type="password"
          placeholder="New Password"
          className="input input-bordered w-full"
          onChange={(e) => {
            setNewPassword(e.target.value);
          }}
        />
      </div>
      <br />
      <div>
        <h2 className="text-xl text-left mb-1">Confirm Password</h2>
        <input
          type="password"
          placeholder="Confirm Password"
          className="input input-bordered w-full"
          onChange={(e) => {
            setConfirmPassword(e.target.value);
          }}
        />
      </div>

      <div className="divider"></div>

      <div className="form-control">
        <label className="label cursor-pointer">
          <span className="label-text">
            I agree to the{" "}
            <span className="text-lime-700">Terms of Service</span>
          </span>
          <input
            type="checkbox"
            defaultChecked
            className="checkbox"
            onChange={() => {
              setTermsAndConditions(!termsAndConditions);
            }}
          />
        </label>
      </div>

      {termsAndConditions ? (
        <button className="btn btn-wide" onClick={handleSubmit}>
          Confirm
        </button>
      ) : (
        <button className="btn btn-wide" disabled>
          Confirm
        </button>
      )}
    </div>
  );
}
